Deference API 수정 구현
decipherhub/decipher-api pull request #13
Opened 2021-11-22 20:38 UTC by swc0620

- [X] erased existing deferenceImage
- [X] modified schema.prisma
- [X] added deferenceSpeaker, deferenceReference, deferencePartnerLogoUrl input & response
- [X] modified deference.service
- [X] updated postman query & mutation examples

2021-11-24 04:54 UTC, JSKeum commented on schema.gql
>    type: String!
타입이 "유투브", "슬라이드 쉐어" 이런거 말하는 거지요?? 어떤게 들어올지 모르니까 enum으로 정해두지 않고 string으로 하는 거고

<img width="955" alt="Screen Shot 2021-11-24 at 1 47 13 PM" src="https://user-images.githubusercontent.com/54926767/143176592-9f01a310-b8c7-49e8-9146-4aaa62b85fd5.png">

2021-11-24 04:54 UTC, JSKeum commented on schema.gql
> +}
이게 optional이 아니라서 모든 input이 다 있어야지만 create가 가능하겠네요. 만드는 입장에선 일부만 넣어 두고 나중에 수정할 수도 있지 않을까 생각도 드는데

2021-11-24 04:54 UTC, JSKeum commented on src/deference/deference.service.ts
>      });
전에 한번 얘기했던대로 한 데이터를 update를 하려면 전체 데이터를 다 넣어줘야 하는거지?? 이렇게 보니까 일부만 수정하는 로직으로  만드는게 더 깔끔할 것 같긴 한데

2021-11-24 04:57 UTC, JSKeum commented
delete는 없네요? 😬

2021-11-25 09:14 UTC, hyemmie reviewed
고생하셨습니다 어드민 작업하면서 같이 리팩토링해봐요...

2021-11-25 09:14 UTC, hyemmie commented on src/deference/deference.service.ts
> +        deferenceSpeaker: {
updateDeferenceInput 보니까 스피커, 레퍼런스, 파트너사로고는 nullable: true라 무조건 들어오지는 않던데 update 문제가 없을까요?!

2021-12-01 08:57 UTC, JSKeum commented
요거 migration 파일 싹 지우고 main rebase 한 다음에 migrate 돌리자 머지 전에

2021-12-01 08:59 UTC, JSKeum requested changes
요거 migration 파일 싹 지우고 main rebase 한 다음에 migrate 돌리자 머지 전에

2021-12-03 12:33 UTC, hyemmie commented
migration 파일들 지금 main 상태에서 deference migration 파일만 덮어씌우게 main rebase해서 수정해뒀습니다 
로컬에서 잘 돌아가요~
그리고 기덕님이 요청하셨던 전체 디퍼런스에 대한 id, year리턴하는 쿼리는 확인해보니 `getDeferences`쿼리로 해결할 수 있어서 따로 추가하지 않았습니다

2021-12-04 10:16 UTC, merged

2021-12-04 10:22 UTC, swc0620 commented on src/deference/deference.service.ts
> +        deferenceSpeaker: {
문제가 있습니다. input에는 nullabe: true라서 data가 안 들어온 상태여도 뒤에 createMany에서는 무조건 연결 relation도 만드는 걸로 되어 있어서 input에서 null로 들어와도 뒤에 service 단에서 error가 납니다. 동일한 문제가 member랑 contact 단에도 발생하고 있습니다

2021-12-04 10:22 UTC, swc0620 commented on src/deference/deference.service.ts
> +        deferenceSpeaker: {
@hyemmie @JSKeum